services:
##############################
# API SERVICE ENVIRONMENT
##############################
  api:
    container_name: api
    restart: always
    image: fullstack-monorepo:latest
    command: ["pnpm", "turbo", "run", "runtime" , "-F=backend-repo"]
    healthcheck:
      test: "env | grep HOME"
      retries: 5
      start_period: 15s
      interval: 30s
      timeout: 60s
    env_file: apps/backend-repo/.env.production
    ports:
      - 4000:4000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - monorepo-networks
##############################
# WEB SERVICE ENVIRONMENT
##############################
  web:
    container_name: web
    restart: always
    image: fullstack-monorepo:latest
    command: ["pnpm", "turbo", "run", "runtime" , "-F=frontend-repo"]
    healthcheck:
      test: "env | grep HOME"
      retries: 5
      start_period: 15s
      interval: 30s
      timeout: 60s
    env_file: apps/frontend-repo/.env.production
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - monorepo-networks
#############################
# NETWORKS SHARING GROUP
#############################
networks:
  monorepo-networks: